### ISSUE TITLE
Support Angular 8

### ISSUE THREAD

**Issue by WandererInVoids** [valor-software/ng2-bootstrap#5242]
### feature request:
Support angular 8
description here https://angular.io/guide/static-query-migration
### Versions of ngx-bootstrap, Angular, and Bootstrap:
ngx-bootstrap: latests
Angular: 8

**Comment by SamanthaAdrichem** [comment]
In the development branch there is this file: ngx-bootstrap/src/timepicker/models/index.ts which has the correct imports.

On version 3.3.0 the imports are incorrect, that is currently the only error i get for angular 8.

**Comment by AhsanAyaz** [comment]
I've got this error when upgrading to v8:
```
ERROR in node_modules/ngx-bootstrap/timepicker/models/index.d.ts(2,38): error TS2307: Cannot find module '@angular/forms/src/directives/control_value_accessor'.
node_modules/ngx-bootstrap/timepicker/models/index.d.ts(3,22): error TS2307: Cannot find module '@angular/core/src/type'.
```

**Comment by SamanthaAdrichem** [comment]
@AhsanAyaz yes me too, that's the file i'm referring too. Apperently there is a new version 4.3.0 which fixes it. Just not sure if thats a bootstrap 4 only or if it's both? My team included 3.2 back then because we need bootstrap 3

**Comment by AhsanAyaz** [comment]
@SamanthaAdrichem yes I don't see the issue after upgrading to 4.3.0.
I'm using Bootstrap 4.

**Comment by ludmilanesvitiy** [comment]
PR in progress: https://github.com/valor-software/ngx-bootstrap/pull/5245

**Comment by smmorris94** [comment]
Trying to update to angular 8 and I am getting this error:

ERROR in node_modules/ngx-bootstrap/collapse/collapse.directive.d.ts(1,34): error TS2307: Cannot find module '@angular/animations'.

Using v 4.3.0 of ngx-bootstrap

**Comment by fchiumeo** [comment]
> 
> 
> Trying to update to angular 8 and I am getting this error:
> 
> ERROR in node_modules/ngx-bootstrap/collapse/collapse.directive.d.ts(1,34): error TS2307: Cannot find module '@angular/animations'.
> 
> Using v 4.3.0 of ngx-bootstrap

install @angular/animations

**Comment by walheredia** [comment]
Guys, this is not a definitive solution, but in case you want to compile the project and continue working, **I have escaped the issue** doing the following (Use it while the correct solution for this problem arrives)

1) Go to the path: node_modules/ngx-bootstrap/timepicker/models/index.d.ts
2) CHANGE these two lines:
`import { ControlValueAccessor } from '@angular/forms/src/directives/control_value_accessor';`
`import { Type } from '@angular/core/src/type';`

by these ones:
`import { ControlValueAccessor } from '@angular/forms';`
`import { Type } from '@angular/core/';`

You'd be able to run the project again.

**Comment by manish-jadli** [comment]
please update ngx-bootstrap above to v3.3 like as: v4,

then you update  remove the error in your terminal :
import { ControlValueAccessor } from '@angular/forms/src/directives/control_value_accessor';
import { Type } from '@angular/core/src/type';

**Comment by ShafeeqAslamT** [comment]
yes, I don't see the issue after upgrading to 4.3.0.
I'm using Bootstrap 4.

**Comment by anjali58** [comment]
Error: Error on worker #1: Error: Failed to find exported name of node (class ButtonRadioGroupDirective {
    constructor(el, cdr) {
        this.el = el;
        this.cdr = cdr;
        this.onChange = Function.prototype;
        this.onTouched = Function.prototype;
    }
    get value() {
        return this._value;
    }
    set value(value) {
        this._value = value;
    }
    writeValue(value) {
        this._value = value;
        this.cdr.markForCheck();
    }
    registerOnChange(fn) {
        this.onChange = fn;
    }
    registerOnTouched(fn) {
        this.onTouched = fn;
    }
})
can u plz solve this ngx-bootstrap problem it says"Entry point 'ngx-bootstrap' contains deep imports " i have  downloaded "npm install ngx-bootstrap@2.0.5 --save" vesrion i dont think its working
